language: node_js
sudo: required
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install -g hexo hexo-cli
- npm install
script:
- git config --global user.name "darluc"
- git config --global user.email "zwz252@gmail.com"
- sed -i "s/__GH_TOKEN__/${GH_TOKEN}/g" ./_config.yml
- hexo generate && hexo deploy
env:
  global:
    secure: jkKLKAitO36gaYpp5O91EVTi05YTVXoA86PFcQ7DG018QqqsF+eCW+erOSHfhVUa13KMSB+7u3NLxW297Mf5i0dLP5PfUL0VDKQS2r1gtL+VaE/fX/9+ORyRpnORxCLWLiuDiTYzk6n8E4qOawfjUD6XWdIYgJEohD4zOuobZGF5wvXcgYLEB1DFkGexpo0lKcnXFUAXTJVKEpwNEvbP8MENuuMNLxsBxSpWc/lCpEjMmsidqLNjYlAbb8R99aC24iOG383ctyGLVJVMsscXe9tkp+IYY2a9t49BBUsFMrxE5YN/OnaalJ7TKsEQC0G1G2WfWaa/a+Gt+61cC3m/82wGSSbFwd1OnD246g6M64tT2nuSDbf/zZ/7Z9m/5sGGOHtLftjkDU3sEKgmGsTuORQvhX/uGmilyHB5m+oyywSRrpfAYDVhJliuNJbyfIx05Eqfq+7yfKNBzAwRaeelf3B84fzIrjt2xiPAbRN12qj0xjQDtPDW1TqBntaBb0RFpfitkB2gc1frKWFrZ0PxzrRH4pCpHU1hSWDvKPi4qtbhPnOyjahBoAfuRx9a8bKfOUbLLFwhPAH1NOdXoSLNYRxYij6kSDWCl7TCSx5bDr3791HMZgVGmI6m+V4v4aVHInYaNmX4dSKfBEE8GkLi8qPDiJtjspSWybTAtwZGxBI=
